services:
  mqtt-broker:
    image: mqtt-broker-iotdata
    container_name: mqtt-broker
    pull_policy: never
    networks:
      storm_network:
    ports:
      - 1883:1883

  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    networks:
      storm_network:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iotdata
    ports:
      - 5432:5432
    volumes:
      - ./timescaledb/dump/iotdata.dump:/backup/iotdata.dump
      - ./timescaledb/dump/restore.sh:/docker-entrypoint-initdb.d/restore.sh
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "psql -U postgres -d iotdata -tAc \"SELECT EXISTS (SELECT 1 FROM plug_forecast_expected LIMIT 1)\" | grep -q t"
        ]
      interval: 5s
      timeout: 5s
      retries: 20

  zookeeper:
    image: zookeeper:3.8.5
    container_name: zookeeper
    hostname: zookeeper
    networks:
      storm_network:
    volumes:
      - ./storm-config/zoo.cfg:/conf/zoo.cfg

  nimbus:
    image: storm:2.5.0
    container_name: nimbus
    hostname: nimbus
    command: sh -c "storm nimbus & storm ui"
    volumes:
      - ./storm-config/nimbus.yaml:/conf/storm.yaml
      - ./storm-topology/target/Storm-IOTdata-1.0-SNAPSHOT-jar-with-dependencies.jar:/apache-storm-2.5.0/Storm-IOTdata-1.0-SNAPSHOT-jar-with-dependencies.jar
    ports:
      - 8080:8080
    restart: always
    networks:
      storm_network:
    depends_on:
      - zookeeper

  supervisor1:
    image: storm:2.5.0
    container_name: supervisor1
    hostname: supervisor1
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
    restart: always
    volumes:
      - ./storm-config/supervisor.yaml:/conf/storm.yaml
    networks:
      storm_network:

  supervisor2:
    image: storm:2.5.0
    container_name: supervisor2
    hostname: supervisor2
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
    restart: always
    volumes:
      - ./storm-config/supervisor.yaml:/conf/storm.yaml
    networks:
      storm_network:

  grafana:
    image: grafana/grafana:13.0.3
    container_name: grafana
    hostname: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes: 
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      storm_network:
    depends_on:
      timescaledb:
        condition: service_healthy

networks:
  storm_network:
    driver: bridge