{
 "title": "Forecast",
 "time": { "from": "2013-09-03T22:00:00.000Z", "to": "2013-09-03T23:30:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "window_size",
    "query": {
     "query": "SELECT DISTINCT window_size\nFROM plug_average_expected \nORDER BY window_size;"
    }
   },
   {
    "name": "house",
    "query": {
     "query": "SELECT DISTINCT house_id\nFROM plug_average_expected \nWHERE window_size = ${window_size}\nORDER BY house_id;"
    }
   },
   {
    "name": "household",
    "query": {
     "query": "SELECT DISTINCT household_id\nFROM plug_average_expected \nWHERE window_size = ${window_size}\nAND house_id = ${house}\nORDER BY household_id;"
    }
   },
   {
    "name": "plug",
    "query": {
     "query": "SELECT DISTINCT plug_id\nFROM plug_average_expected \nWHERE window_size = ${window_size}\nAND house_id = ${house}\nAND household_id = ${household}\nORDER BY plug_id;"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Plug forecast",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "dataset": "iotdata",
     "rawSql": "SELECT\n    timestamp,\n    average_load as average_load_expected\nFROM plug_average_expected \nWHERE window_size = ${window_size}\nAND house_id = ${house}\nAND household_id = ${household}\nAND plug_id = ${plug}\nORDER BY timestamp;"
    },
    {
     "dataset": "iotdata",
     "rawSql": "SELECT\n    timestamp,\n    average_load\nFROM plug_average\nWHERE window_size = ${window_size}\nAND house_id = ${house}\nAND household_id = ${household}\nAND plug_id = ${plug}\nORDER BY timestamp;"
    },
    {
     "dataset": "iotdata",
     "rawSql": "SELECT\n    timestamp,\n    forecast_load as forecast_load_expected\nFROM plug_forecast_expected \nWHERE window_size = ${window_size}\nAND house_id = ${house}\nAND household_id = ${household}\nAND plug_id = ${plug}\nORDER BY timestamp;"
    },
    {
     "dataset": "iotdata",
     "rawSql": "SELECT\n    timestamp,\n    forecast_load\nFROM plug_forecast\nWHERE window_size = ${window_size}\nAND house_id = ${house}\nAND household_id = ${household}\nAND plug_id = ${plug}\nORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "House forecast",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "dataset": "iotdata",
     "rawSql": "SELECT\n    timestamp,\n    average_load as average_load_expected\nFROM house_average_expected \nWHERE window_size = ${window_size}\nAND house_id = ${house}\nORDER BY timestamp;"
    },
    {
     "dataset": "iotdata",
     "rawSql": "SELECT\n    timestamp,\n    average_load\nFROM house_average\nWHERE window_size = ${window_size}\nAND house_id = ${house}\nORDER BY timestamp;"
    },
    {
     "dataset": "iotdata",
     "rawSql": "SELECT\n    timestamp,\n    forecast_load as forecast_load_expected\nFROM house_forecast_expected \nWHERE window_size = ${window_size}\nAND house_id = ${house}\nORDER BY timestamp;"
    },
    {
     "dataset": "iotdata",
     "rawSql": "SELECT\n    timestamp,\n    forecast_load\nFROM house_forecast\nWHERE window_size = ${window_size}\nAND house_id = ${house}\nORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "Plug forecast latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "iotdata",
     "rawSql": "SELECT\n    timestamp,\n    prediction_latency as forecast_latency\nFROM plug_forecast \nWHERE window_size = ${window_size}\nAND house_id = ${house}\nAND household_id = ${household}\nAND plug_id = ${plug}\nORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "House forecast",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "iotdata",
     "rawSql": "SELECT\n    timestamp,\n    prediction_latency as forecast_latency\nFROM house_forecast \nWHERE window_size = ${window_size}\nAND house_id = ${house}\nORDER BY timestamp;"
    }
   ]
  }
 ]
}